### PR TITLE
Updated COMPONENT_VERSION file for release-2.8

### PR DESCRIPTION
**Pull request by dislbenn**
Signed-off-by: dislbenn <dbennett@redhat.com>

**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>

### CODE REVIEW

**Review by jlpadilla — CHANGES_REQUESTED** [review]
Builds have been working without this file, so I don't think it's required anymore. Let's not add it unless required to keep project simple..

**Review by jlpadilla — APPROVED** [review]
/lgtm
/hold

Must merge https://github.com/openshift/release/pull/35425 first.

**Comment by dislbenn** [comment]
/override ci/prow/deploy-and-run-e2e

I will override this job only because it is running a placeholder for the e2e tests that will be added within the future. Currently the job only execute the following:

```bash
echo "[TODO] Run e2e test here."
```

**Pull request merged**
